/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.dif.didcomm.demo

import org.dif.peerdid.isPeerDID
import kotlin.test.Test
import kotlin.test.assertTrue

class DIDCommDemoTest {

    @Test
    fun testCreatePeerDid() {
        val demo = DIDCommDemo()
        val peerDID = demo.createPeerDID()
        assertTrue(isPeerDID(peerDID))
    }
}
